### ISSUE TITLE
Geoconnex connection Stage 1 -- PIDs

### ISSUE THREAD

**Issue by ksonda** [NMWDI/pygeoapi_config#1]
OK first thing is to get geoconnex PIDS up 

4 Steps:

1. Register PIDs and redirects with [geoconnex.us](https://github.com/internetofwater/geoconnex.us/blob/master/CONTRIBUTING.md), probably with a [regex redirect](https://github.com/internetofwater/geoconnex.us/issues/new?assignees=dblodgett-usgs%2C+ksonda&labels=PID+request&template=request-regex-redirect.md&title=%5Bregex+redirect+request%5D)

These pygeoapi pages of the pattern https://wells.newmexicowaterdata.org/collections/wells/items/{id} should have pids of a pattern like

https://geoconnex.us/nmwdi/wells/{id}

or possibly

https://geoconnex.us/nmwdi/{agency}/wells/{id} 

depending on how you'd like to represent the data.

2. Make sure you are running a version of pygeoapi with [this PR](https://github.com/geopython/pygeoapi/pull/469) built. The docker image `internetofwater/pygeoapi-geoconnex:contextmod` works.

3. Add a field called ```uri``` in ```wells.gpkg``` which has the appropriate ```https://geoconnex.us/nmwdi``` - based PID from Step 1 in it.

4. Modify wdi.config.yml at the bottom as follows:

```provider:
                        name: SQLiteGPKG
                        data: data/wells.gpkg
                        table: wells
                        id_field: id
                        uri_field: uri

```

**Comment by jirhiker** [comment]
I moved each agency to its own collection
so

wells.newmexicowaterdata.org/collections/nmbgmr_wells/items/{id}
wells.newmexicowaterdata.org/collections/ose_wells/items/{id}

**Comment by ksonda** [comment]
However you want to do it. The PIDs can be 1:1, so like

https://geoconnex.us/nmwdi/wells/NMWDI-OSE-100001 can go to wells.newmexicowaterdata.org/collections/ose_wells/items/NMWDI-OSE-100001 

while 

https://geoconnex.us/nmwdi/wells/NMWDI-NMBGMR-100001 can go to wells.newmexicowaterdata.org/collections/nmbgmr_wells/items/NMWDI-NMBGMR-100001 

or they can be regular expression matches, but to do that you would need separate nmwdi namespaces for each agency, like

https://geoconnex.us/nmwdi/ose/wells/{any regular expression} can go to wells.newmexicowaterdata.org/collections/ose_wells/items/{any regular expression} 

while

https://geoconnex.us/nmwdi/nmbgmr/wells/{any regular expression} can go to wells.newmexicowaterdata.org/collections/nmbgmr_wells/items/{any regular expression} 

Eventually I think we want 1:1 matches but because its so early you might want to do regular expressions so you dont have to update the PID list every time you get some new data in. In which case I think the agency-by-agency namespace with regular expression matches is the way to go on the geoconnex side.

**Comment by ksonda** [comment]
The way you set it up it has to be 1:1, but that's fine. Just noting to myself here. https://geoconnex.us/nmwdi/ose/wells/LRG-542 mapping to http://wells.newmexicowaterdata.org/collections/ose_wells/items/NMWDI-OSE-000001 has to be a 1:1 match.
